  version: '2'
  services:
    db:
      build:
        context: ./docker/db
      restart: always
      networks:
        - sn-network
      env_file:
        .env
      container_name: golang_db
      ports:
        - "3306:3306"
      tty: true
    app:
      build:
        context: ./
      networks:
        - sn-network
      env_file:
        .env
      container_name: golang_app
      ports:
        - "3004:3004"
      tty: true
      depends_on:
        - db
      links:
        - db
  networks:
    sn-network:
      driver: "bridge"